### ISSUE TITLE
Can you provide code for train and test

### ISSUE THREAD

**Issue by TonyLiangJunsheng** [yuanming-hu/fc4#1] opened 2018-04-17 05:14 UTC
I am interest about your experiments on color constancy, can you provide more code or useful tutorials for train and test the FC4 model.

**Comment by yuanming-hu** [comment] 2018-04-26 03:35
Hi,

Training and test code is posted now. I'm still testing if it works well after my clean-up, but it probably does now.

Best,
Yuanming

**Comment by yuanming-hu** [comment] 2018-04-26 05:12
It seems there is some slight issue in the config.py file that determines data augmentation. config.py looks a bit out of sync and I'm working on it now. It should be fixed very quickly.

**Comment by TonyLiangJunsheng** [comment] 2018-04-26 08:41
Thank you. I just tried to rewrite it using caffe, but the diff in angular error make me crazy. You work saved me a lot of time. By the way, can you provide the supplementary material for detail deduction:)

**Comment by yuanming-hu** [comment] 2018-04-26 14:36
I think the issue is fixed now. That's not suprising... When I was developing I spent almost three weeks to figure out the best parameters...

Also, given the dataset is too small for deep learning, I don't even think a small diff in angular error (say, 0.1) is significant.

I will add the inference code tonight.

**Comment by yuanming-hu** [comment] 2018-04-26 14:37
Merged into #2

**Closed by yuanming-hu** 2018-04-26 14:37 UTC
